(() => {
'use strict';
const C=window.NGAJI_CONFIG||{}; let supa=null;
try{if(window.supabase&&C.SUPABASE_URL)supa=window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY)}catch(e){console.warn(e)}
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const state={role:'guest',user:null,tab:'utama',slide:0,adminTab:'ringkasan',teacherTab:'profil',studentTab:'profil'};
const demo={student:{id:'101010101010',name:'Aiman Hakim',phone:'012-888 2026',dob:'10/10/2010',address:'Eristana, Kuala Lumpur',teachers:['Ustaz Ahmad','Ustazah Mariam'],attendance:88,absent:3},teacher:{phone:'01234567890',password:'123456',name:'Ustaz Ahmad Firdaus',email:'ahmad@example.com',capacity:30,students:18},admin:{id:'ngaji_admin',password:'123456',name:'Pentadbir Ngaji'},results:[{date:'15 Jun 2026',name:'Penilaian Pertengahan Tahun',score:84,assessor:'Ustaz Ahmad Firdaus',comment:'Bacaan semakin lancar. Fokus pada makhraj ض dan ظ.',items:{Kehadiran:27,Tajwid:12,Makhraj:9,Kelancaran:8,'Adab & Sebutan':5,'Hafazan / Sasaran':7,Penglibatan:16}},{date:'18 Dis 2025',name:'Penilaian Akhir Tahun',score:78,assessor:'Ustazah Mariam',comment:'Kemajuan baik dan perlu latihan waqaf.',items:{Kehadiran:25,Tajwid:11,Makhraj:8,Kelancaran:7,'Adab & Sebutan':5,'Hafazan / Sasaran':7,Penglibatan:15}}]};
const publicTabs=['utama','takwim','asatizah','dokumen','maklumbalas'];
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function modal(html){$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal">${html}</div></div>`}
function closeModal(){$('#modalRoot').innerHTML=''}
function nav(){const common=state.role==='guest'?[]:publicTabs; let own=[];if(state.role==='student')own=['profil','kedatangan','keputusan'];if(state.role==='teacher')own=['profil','pelajar','kedatangan','penilaian','cuti'];if(state.role==='admin')own=['ringkasan','kandungan','pelajar','asatizah','kedatangan','takwim','penilaian','tetapan'];const tabs=[...own,...common.filter(x=>!own.includes(x))];$('#mainNav').innerHTML=tabs.map(x=>`<button class="nav-btn ${(currentTab()===x)?'active':''}" data-tab="${x}">${label(x)}</button>`).join('')+(state.role!=='guest'?'<button class="nav-btn" data-action="logout">Log keluar</button>':'');$('#userBadge').classList.toggle('hidden',state.role==='guest');$('#userBadge').textContent=state.user?.name||''}
function label(x){return ({utama:'Utama',takwim:'Takwim',asatizah:'Asatizah',dokumen:'Dokumen',maklumbalas:'Maklum Balas',profil:'Profil',pelajar:'Pelajar',kedatangan:'Kedatangan',keputusan:'Keputusan',penilaian:'Penilaian',cuti:'Cuti',ringkasan:'Ringkasan',kandungan:'Kandungan',tetapan:'Tetapan'})[x]||x}
function currentTab(){return state.role==='student'?state.studentTab:state.role==='teacher'?state.teacherTab:state.role==='admin'?state.adminTab:state.tab}
function setTab(t){if(state.role==='student')state.studentTab=t;else if(state.role==='teacher')state.teacherTab=t;else if(state.role==='admin')state.adminTab=t;else state.tab=t;render()}
function home(){state.role='guest';state.user=null;state.tab='utama';renderLanding()}
function renderLanding(){nav();$('#app').innerHTML=`<section class="hero"><div><div class="chip" style="display:inline-block">Pembelajaran Al-Quran · Komuniti Eristana</div><h1>Selamat Datang ke <span>Portal Kelas Ngaji</span> @ Surau Eristana</h1><p>Akses maklumat kelas, kehadiran, penilaian, takwim dan pengurusan peserta dalam satu portal.</p><div class="role-grid">${[['🌐','Umum','Maklumat, takwim dan dokumen awam'],['🎓','Pelajar','Profil, kedatangan dan keputusan'],['📖','Asatizah','Kelas, pelajar dan penilaian'],['⚙️','Pentadbir','Urus portal dan konfigurasi']].map(x=>`<button class="role-card" data-role="${x[1].toLowerCase()}"><i>${x[0]}</i><b>${x[1]}</b><span>${x[2]}</span></button>`).join('')}</div></div><div class="hero-logo"><img src="assets/logo.png" alt="Logo Surau Ar Raudhah Eristana"></div></section>`}
function page(title,sub,body){return `<section class="page"><div class="page-head"><div><h1>${title}</h1><p>${sub||''}</p></div></div>${body}</section>`}
function publicView(t){if(t==='utama')return page('Utama','Maklumat terkini Kelas Ngaji Surau Eristana',`<div class="grid"><div class="span-8"><div class="slider">${['Majlis Ilmu, Membina Ummah','Bacaan Bertajwid, Hati Terpimpin','Belajar Bersama, Istiqamah Bersama'].map((x,i)=>`<div class="slide ${['one','two','three'][i]} ${state.slide===i?'active':''}"><h2>${x}</h2><p>Kelas bimbingan Al-Quran untuk komuniti Eristana.</p></div>`).join('')}<div class="slider-controls"><button data-action="prev-slide">‹</button><button data-action="next-slide">›</button></div></div></div><div class="span-4 card"><h2>Pengumuman</h2><div class="announcement"><b>Pendaftaran Kelas Dibuka</b><p>Permohonan baharu boleh dikemukakan melalui pautan pendaftaran.</p></div><div class="announcement"><b>Penilaian Pertengahan Tahun</b><p>Maklumat tarikh akan dikemas kini dalam Takwim.</p></div></div></div>`);
if(t==='takwim')return calendarView();if(t==='asatizah')return teachersView();if(t==='dokumen')return docsView();return feedbackView()}
function calendarView(){const days=['Ahd','Isn','Sel','Rab','Kha','Jum','Sab'];let cells=days.map(d=>`<div class="cal-cell cal-head">${d}</div>`).join('');for(let i=1;i<=30;i++){let e=i===6?'Cuti Umum':i===14?'Penilaian':i===21?'Cuti Sekolah':'';cells+=`<div class="cal-cell"><b>${i}</b>${e?`<span class="event">${e}</span>`:''}</div>`}return page('Takwim','Cuti umum, jadual kelas, peperiksaan dan penilaian',`<div class="card"><div class="page-head"><h2>September 2026</h2><button class="btn light">Hari Ini</button></div><div class="calendar">${cells}</div></div>`)}
function teachersView(){return page('Asatizah','Profil pengajar dan kekosongan kelas',`<div class="grid">${[['AF','Ustaz Ahmad Firdaus','Tajwid & Tilawah','Isnin, Rabu · 8:30 malam','12 kekosongan'],['MA','Ustazah Mariam Abdullah','Iqra & Asas Bacaan','Sabtu · 9:00 pagi','5 kekosongan'],['HH','Ustaz Hafiz Hakim','Hafazan & Tarannum','Ahad · 9:00 pagi','Penuh']].map(x=>`<div class="card span-4 teacher-card"><div class="avatar">${x[0]}</div><div><h3>${x[1]}</h3><p>${x[2]}</p><div class="chips"><span class="chip">${x[3]}</span><span class="chip">${x[4]}</span></div></div></div>`).join('')}</div>`)}
function docsView(){return page('Dokumen','Muat turun bahan pembelajaran dan dokumen kelas',`<div class="card">${[['Borang Pendaftaran Pelajar','PDF'],['Panduan Kelas Ngaji','PDF'],['Jadual Kelas Semasa','Pautan'],['Borang Maklum Balas','Pautan']].map(x=>`<div class="doc-row"><div><b>${x[0]}</b><div class="muted">${x[1]}</div></div><button class="btn light" data-action="demo">Buka</button></div>`).join('')}</div>`)}
function feedbackView(){let form=C.GOOGLE_FORM_EMBED_URL?`<iframe title="Borang Maklum Balas" src="${C.GOOGLE_FORM_EMBED_URL}" width="100%" height="540" frameborder="0">Memuatkan…</iframe>`:`<div class="empty">Masukkan Google Form embed URL dalam <b>config.js</b>.</div>`;let map=C.MAP_EMBED_URL?`<iframe title="Peta Surau" src="${C.MAP_EMBED_URL}" width="100%" height="290" frameborder="0"></iframe>`:`<div class="empty">Masukkan Google Maps embed URL dalam <b>config.js</b>.</div>`;return page('Maklum Balas','Hubungi pentadbir atau hantarkan cadangan',`<div class="grid"><div class="card span-7"><h2>Borang Maklum Balas</h2>${form}</div><div class="span-5"><div class="card"><h2>Hubungi Kami</h2><p><b>Surau Ar Raudhah Eristana</b></p><p class="muted">Telefon: Dikemas kini oleh pentadbir<br>E-mel: Dikemas kini oleh pentadbir</p></div><div class="card" style="margin-top:18px"><h2>Lokasi</h2>${map}</div></div></div>`)}
function login(kind){if(kind==='pelajar'){modal(`<h2>Log Masuk Pelajar</h2><p>Masukkan nombor Kad Pengenalan tanpa sengkang.</p><form id="studentLogin"><div class="field"><label>No. Kad Pengenalan</label><input name="id" inputmode="numeric" required placeholder="101010101010"></div><div class="demo-note">Demo: 101010101010</div><div class="modal-actions"><button type="button" class="btn light" data-action="close-modal">Batal</button><button class="btn">Semak Rekod</button></div></form>`)}else if(kind==='asatizah'){modal(loginForm('Log Masuk Asatizah','teacherLogin','No. telefon','01234567890','Demo: 01234567890 / 123456'))}else{modal(loginForm('Log Masuk Pentadbir','adminLogin','ID / E-mel','ngaji_admin','Demo: ngaji_admin / 123456'))}}
function loginForm(title,id,label,placeholder,note){return `<h2>${title}</h2><form id="${id}"><div class="field"><label>${label}</label><input name="id" required placeholder="${placeholder}"></div><div class="field" style="margin-top:12px"><label>Kata laluan</label><input type="password" name="password" required></div><div class="demo-note">${note}</div><div class="modal-actions"><button type="button" class="btn light" data-action="close-modal">Batal</button><button class="btn">Log Masuk</button></div></form>`}
function studentView(t){if(publicTabs.includes(t))return publicView(t);if(t==='profil')return page('Profil Pelajar','Maklumat peribadi dan penempatan kelas',`<div class="grid"><div class="card span-8"><h2>${demo.student.name}</h2><div class="form-grid">${[['No. Kad Pengenalan',demo.student.id,'disabled'],['Telefon',demo.student.phone,''],['Tarikh Lahir',demo.student.dob,'disabled'],['Alamat',demo.student.address,'']].map(x=>`<div class="field"><label>${x[0]}</label><input value="${x[1]}" ${x[2]}></div>`).join('')}</div><div class="modal-actions"><button class="btn" data-action="save">Simpan Perubahan</button></div></div><div class="card span-4"><h3>Asatizah Ditugaskan</h3>${demo.student.teachers.map(x=>`<div class="list-row"><b>${x}</b><span class="status">Aktif</span></div>`).join('')}<p class="muted">Pertukaran asatizah hanya tersedia ketika tetingkap pemilihan dibuka oleh pentadbir.</p></div></div>`);if(t==='kedatangan')return attendanceStudent();return resultsView()}
function attendanceStudent(){const months=['Jan','Feb','Mac','Apr','Mei','Jun','Jul','Ogos'];return page('Kedatangan','Ringkasan dan rekod kehadiran bulanan',`<div class="grid"><div class="card span-4"><div class="muted">Kehadiran</div><div class="stat">${demo.student.attendance}%</div><div class="progress"><span style="width:${demo.student.attendance}%"></span></div></div><div class="card span-4"><div class="muted">Tidak Hadir</div><div class="stat" style="color:var(--danger)">${demo.student.absent} hari</div></div><div class="card span-4"><div class="muted">Status</div><div class="stat">Baik</div></div><div class="card span-12"><h2>Status Bulanan</h2><table><thead><tr><th>Bulan</th><th>Hadir</th><th>Tidak Hadir</th><th>Peratus</th></tr></thead><tbody>${months.map((m,i)=>`<tr><td>${m}</td><td>${3+i%2}</td><td>${i%4===0?1:0}</td><td><span class="status">${i%4===0?'75':'100'}%</span></td></tr>`).join('')}</tbody></table></div></div>`)}
function resultsView(){return page('Keputusan','Keputusan terkini dipaparkan di bahagian atas',`<div class="grid">${demo.results.map((r,i)=>`<div class="card span-6"><span class="status">${r.date}</span><h2>${r.name}</h2><div class="stat">${r.score}/100</div><p class="muted">Dinilai oleh ${r.assessor}</p><button class="btn light" data-result="${i}">Lihat Pecahan</button></div>`).join('')}</div>`)}
function resultModal(i){const r=demo.results[i];modal(`<h2>${r.name}</h2><div class="stat">${r.score}/100</div><p><b>Penilai:</b> ${r.assessor}</p><table>${Object.entries(r.items).map(x=>`<tr><td>${x[0]}</td><td><b>${x[1]}</b></td></tr>`).join('')}</table><p><b>Ulasan:</b><br>${r.comment}</p><div class="modal-actions"><button class="btn" data-action="close-modal">Tutup</button></div>`)}
function teacherView(t){if(publicTabs.includes(t))return publicView(t);if(t==='profil')return page('Profil Asatizah','Urus profil dan slot ketersediaan',`<div class="grid"><div class="card span-7"><div class="form-grid"><div class="field"><label>Nama</label><input value="${demo.teacher.name}"></div><div class="field"><label>No. Telefon</label><input value="${demo.teacher.phone}"></div><div class="field full"><label>E-mel</label><input value="${demo.teacher.email}"></div></div><div class="modal-actions"><button class="btn" data-action="save">Simpan</button></div></div><div class="card span-5"><h2>Ketersediaan</h2><div class="list-row"><b>Isnin · 8:30 malam</b><span class="status">Mingguan</span></div><div class="list-row"><b>Rabu · 8:30 malam</b><span class="status">Mingguan</span></div><button class="btn light" data-action="demo">+ Tambah Slot</button></div></div>`);if(t==='pelajar')return teacherStudents();if(t==='kedatangan')return teacherAttendance();if(t==='penilaian')return teacherAssessment();return leaveView()}
function teacherStudents(){return page('Pelajar','Pelajar yang ditugaskan kepada kelas anda',`<div class="card"><div class="page-head"><div><h2>${demo.teacher.students} / ${demo.teacher.capacity} pelajar</h2></div><button class="btn" data-action="demo">+ Cari / Tambah Pelajar</button></div><table><thead><tr><th>Nama</th><th>Mula</th><th>Tamat</th><th>Status</th></tr></thead><tbody>${['Aiman Hakim','Nur Aisyah','Muhammad Adam','Siti Hawa','Danish Irfan'].map((n,i)=>`<tr><td>${n}</td><td>01/01/2026</td><td>${i===4?'31/12/2026':'-'}</td><td><span class="status">Aktif</span></td></tr>`).join('')}</tbody></table></div>`)}
function teacherAttendance(){return page('Kedatangan Pelajar','Tarikh lalai ialah hari ini',`<div class="card"><div class="field" style="max-width:240px;margin-bottom:15px"><label>Tarikh Kelas</label><input type="date" value="2026-09-23"></div><table><thead><tr><th>Pelajar</th><th>Hadir</th><th>Tidak Hadir</th><th>Catatan</th></tr></thead><tbody>${['Aiman Hakim','Nur Aisyah','Muhammad Adam','Siti Hawa'].map((n,i)=>`<tr><td>${n}</td><td><input type="radio" name="a${i}" checked></td><td><input type="radio" name="a${i}"></td><td><input placeholder="Catatan"></td></tr>`).join('')}</tbody></table><div class="modal-actions"><button class="btn" data-action="save">Simpan Kehadiran</button></div></div>`)}
function teacherAssessment(){return page('Penilaian','Tetingkap penilaian dibuka sehingga 30 September 2026',`<div class="card"><div class="announcement"><b>Tetingkap Aktif</b><p>Asatizah boleh mengisi dan mengemas kini penilaian dalam tempoh ini.</p></div><table><thead><tr><th>Pelajar</th><th>Status</th><th>Skor</th><th>Tindakan</th></tr></thead><tbody>${['Aiman Hakim','Nur Aisyah','Muhammad Adam'].map((n,i)=>`<tr><td>${n}</td><td><span class="status">${i?'Draf':'Selesai'}</span></td><td>${i?'--':'84'}</td><td><button class="btn light" data-action="demo">${i?'Nilai':'Semak / Cetak'}</button></td></tr>`).join('')}</tbody></table></div>`)}
function leaveView(){return page('Cuti Asatizah','Tempoh cuti mengatasi semua slot kelas dalam tarikh berkenaan',`<div class="grid"><div class="card span-5"><h2>Tambah Cuti</h2><div class="form-grid"><div class="field"><label>Tarikh Mula</label><input type="date"></div><div class="field"><label>Tarikh Tamat</label><input type="date"></div><div class="field full"><label>Catatan</label><textarea></textarea></div></div><div class="modal-actions"><button class="btn" data-action="save">Simpan</button></div></div><div class="card span-7"><h2>Rekod Cuti</h2><div class="empty">Tiada rekod cuti aktif.</div></div></div>`)}
function adminView(t){if(publicTabs.includes(t))return publicView(t);if(t==='ringkasan')return page('Dashboard Pentadbir','Ringkasan operasi portal',`<div class="grid">${[['128','Pelajar'],['6','Asatizah'],['88%','Kehadiran'],['Aktif','Tetingkap Penilaian']].map(x=>`<div class="card span-4"><div class="stat">${x[0]}</div><div class="muted">${x[1]}</div></div>`).join('')}<div class="card span-12"><h2>Tindakan Pantas</h2><div class="chips"><button class="btn">+ Pelajar</button><button class="btn secondary">+ Asatizah</button><button class="btn light">Muat Naik Senarai</button><button class="btn gold">Buka Penilaian</button></div></div></div>`);if(t==='kandungan')return manageContent();if(t==='pelajar'||t==='asatizah')return managePeople(t);if(t==='kedatangan')return manageAttendance();if(t==='takwim')return manageCalendar();if(t==='penilaian')return manageAssessment();return settingsView()}
function manageContent(){return page('Kandungan Portal','Urus pengumuman, slaid utama, dokumen dan maklumat hubungan',`<div class="grid"><div class="card span-6"><h2>Pengumuman</h2><div class="field"><label>Tajuk</label><input value="Pendaftaran Kelas Dibuka"></div><div class="field"><label>Kandungan</label><textarea>Pendaftaran pelajar baharu kini dibuka.</textarea></div><button class="btn" data-action="save">Simpan</button></div><div class="card span-6"><h2>Dokumen Awam</h2><div class="field"><label>Nama Dokumen</label><input></div><div class="field"><label>URL / Fail</label><input type="url"></div><button class="btn" data-action="save">Tambah</button></div></div>`)}
function managePeople(type){let teacher=type==='asatizah';return page(teacher?'Pengurusan Asatizah':'Pengurusan Pelajar',`Tambah, muat naik, sunting dan tetapkan ${teacher?'had pelajar':'asatizah'}`,`<div class="card"><div class="page-head"><div><input placeholder="Cari rekod..."></div><div><button class="btn light" data-action="demo">Muat Naik CSV</button> <button class="btn" data-action="demo">+ Rekod Baharu</button></div></div><table><thead><tr><th>${teacher?'Nama Asatizah':'Nama Pelajar'}</th><th>ID / Telefon</th><th>${teacher?'Pelajar':'Asatizah'}</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>${(teacher?['Ustaz Ahmad Firdaus','Ustazah Mariam Abdullah']:['Aiman Hakim','Nur Aisyah','Muhammad Adam']).map((n,i)=>`<tr><td>${n}</td><td>${teacher?'012-000 000'+i:'10101010101'+i}</td><td>${teacher?(18+i):'Ustaz Ahmad'}</td><td><span class="status">Aktif</span></td><td><button class="btn light" data-action="demo">Sunting</button></td></tr>`).join('')}</tbody></table></div>`)}
function manageAttendance(){return page('Semakan Kedatangan','Semak dan override rekod dengan jejak audit',`<div class="card"><table><thead><tr><th>Tarikh</th><th>Pelajar</th><th>Asatizah</th><th>Status</th><th>Tindakan</th></tr></thead><tbody><tr><td>23/09/2026</td><td>Aiman Hakim</td><td>Ustaz Ahmad</td><td><span class="status">Hadir</span></td><td><button class="btn light" data-action="demo">Override</button></td></tr></tbody></table></div>`)}
function manageCalendar(){return page('Pengurusan Takwim','Tambah cuti umum, cuti sekolah, peperiksaan dan penilaian',`<div class="grid"><div class="card span-5"><h2>Acara Baharu</h2><div class="field"><label>Jenis</label><select><option>Cuti Umum</option><option>Cuti Sekolah</option><option>Peperiksaan</option><option>Penilaian</option></select></div><div class="field"><label>Tarikh</label><input type="date"></div><div class="field"><label>Tajuk</label><input></div><button class="btn" data-action="save">Tambah</button></div><div class="span-7">${calendarView().match(/<div class="card">[\s\S]*<\/div><\/section>/)?.[0]?.replace('</section>','')||''}</div></div>`)}
function manageAssessment(){return page('Konfigurasi Penilaian','Tetapkan tetingkap, kekerapan dan wajaran komponen',`<div class="grid"><div class="card span-5"><h2>Tetingkap Penilaian</h2><div class="field"><label>Mula</label><input type="datetime-local"></div><div class="field"><label>Tamat</label><input type="datetime-local"></div><div class="chips"><button class="btn">Buka Tetingkap</button><button class="btn danger">Tutup</button></div></div><div class="card span-7"><h2>Wajaran (%)</h2>${[['Kehadiran',30],['Tajwid',15],['Makhraj',12],['Kelancaran',10],['Adab & Sebutan',5],['Hafazan / Sasaran',8],['Penglibatan',20]].map(x=>`<div class="list-row"><b>${x[0]}</b><input type="number" value="${x[1]}" min="0" max="100" style="width:80px"></div>`).join('')}<div class="modal-actions"><button class="btn" data-action="save">Simpan Wajaran</button></div></div></div>`)}
function settingsView(){return page('Tetapan Sistem','Medan boleh sunting, kapasiti kelas dan integrasi',`<div class="grid"><div class="card span-6"><h2>Had Kelas</h2><div class="field"><label>Maksimum pelajar bagi setiap asatizah</label><input type="number" value="30"></div><button class="btn" data-action="save">Simpan</button></div><div class="card span-6"><h2>Medan Boleh Disunting</h2>${['Telefon','Alamat','E-mel','Pilihan Asatizah'].map((x,i)=>`<div class="list-row"><b>${x}</b><input type="checkbox" ${i<2?'checked':''}></div>`).join('')}</div><div class="card span-12"><h2>Status Integrasi</h2><p><span class="status">Supabase dikonfigurasi</span></p><p class="muted">Jalankan fail <b>supabase-schema.sql</b> di SQL Editor sebelum menukar DEMO_MODE kepada false.</p></div></div>`)}
function render(){nav();let t=currentTab();$('#app').innerHTML=state.role==='student'?studentView(t):state.role==='teacher'?teacherView(t):state.role==='admin'?adminView(t):publicView(t);$('#app').focus()}
function authSubmit(e){e.preventDefault();let f=new FormData(e.target);if(e.target.id==='studentLogin'){let id=String(f.get('id')).replace(/\D/g,'');if(id!==demo.student.id){modal(`<h2>Rekod tidak dijumpai</h2><p>Sila daftar atau hubungi pentadbir.</p><div class="modal-actions"><a class="btn light" href="${C.REGISTRATION_URL}">Daftar</a><button class="btn" data-action="close-modal">Tutup</button></div>`);return}state.role='student';state.user=demo.student;state.studentTab='profil'}else if(e.target.id==='teacherLogin'){if(f.get('id')!==demo.teacher.phone||f.get('password')!==demo.teacher.password){toast('No. telefon atau kata laluan tidak sah');return}state.role='teacher';state.user=demo.teacher;state.teacherTab='profil'}else{if(f.get('id')!==demo.admin.id||f.get('password')!==demo.admin.password){toast('ID atau kata laluan tidak sah');return}state.role='admin';state.user=demo.admin;state.adminTab='ringkasan'}closeModal();render()}
document.addEventListener('click',e=>{let a=e.target.closest('[data-action],[data-role],[data-tab],[data-result]');if(!a)return;if(a.dataset.action==='home'){e.preventDefault();home()}if(a.dataset.action==='toggle-menu')$('#mainNav').classList.toggle('open');if(a.dataset.action==='close-modal')closeModal();if(a.dataset.action==='logout')home();if(a.dataset.action==='save')toast('Perubahan disimpan dalam mod demo');if(a.dataset.action==='demo')toast('Fungsi tersedia selepas pangkalan data diaktifkan');if(a.dataset.action==='next-slide'){state.slide=(state.slide+1)%3;render()}if(a.dataset.action==='prev-slide'){state.slide=(state.slide+2)%3;render()}if(a.dataset.role){let r=a.dataset.role;if(r==='umum'){state.role='guest';state.tab='utama';render()}else login(r)}if(a.dataset.tab){setTab(a.dataset.tab);$('#mainNav').classList.remove('open')}if(a.dataset.result)resultModal(Number(a.dataset.result))});
document.addEventListener('submit',authSubmit);document.querySelector('#year').textContent=new Date().getFullYear();renderLanding();setInterval(()=>{if(currentTab()==='utama'&&state.role!=='admin'){state.slide=(state.slide+1)%3;$$('.slide').forEach((x,i)=>x.classList.toggle('active',i===state.slide))}},10000);
})();
