-- Portal Kelas Ngaji @ Surau Eristana
-- Semua jadual menggunakan awalan ngaji_. Jalankan dalam Supabase SQL Editor.
create extension if not exists pgcrypto;
create table if not exists ngaji_users (id uuid primary key default gen_random_uuid(), role text not null check(role in ('admin','teacher','student')), login_id text unique not null, password_hash text, is_active boolean default true, created_at timestamptz default now());
create table if not exists ngaji_students (id uuid primary key default gen_random_uuid(), user_id uuid references ngaji_users(id), ic_no text unique not null, full_name text not null, phone text, email text, birth_date date, address text, profile jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists ngaji_teachers (id uuid primary key default gen_random_uuid(), user_id uuid references ngaji_users(id), phone text unique not null, full_name text not null, email text, bio text, expertise text[], capacity int default 30, profile jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists ngaji_teacher_availability (id bigint generated always as identity primary key, teacher_id uuid references ngaji_teachers(id) on delete cascade, start_time time not null, end_time time, recurrence text check(recurrence in ('once','daily','weekly','monthly')), weekday int, effective_date date, end_date date);
create table if not exists ngaji_teacher_leave (id bigint generated always as identity primary key, teacher_id uuid references ngaji_teachers(id) on delete cascade, start_date date not null, end_date date not null, notes text);
create table if not exists ngaji_student_teachers (id bigint generated always as identity primary key, student_id uuid references ngaji_students(id) on delete cascade, teacher_id uuid references ngaji_teachers(id) on delete cascade, start_date date not null default current_date, end_date date, unique(student_id,teacher_id,start_date));
create table if not exists ngaji_attendance (id bigint generated always as identity primary key, student_id uuid references ngaji_students(id), teacher_id uuid references ngaji_teachers(id), class_date date not null, status text not null check(status in ('present','absent','excused','cancelled')), notes text, recorded_by uuid references ngaji_users(id), overridden_by uuid references ngaji_users(id), override_reason text, updated_at timestamptz default now(), unique(student_id,teacher_id,class_date));
create table if not exists ngaji_assessment_windows (id bigint generated always as identity primary key, title text not null, starts_at timestamptz not null, ends_at timestamptz not null, is_open boolean default false, assessment_no int, year int, created_by uuid references ngaji_users(id));
create table if not exists ngaji_assessment_items (id bigint generated always as identity primary key, item_key text unique not null, label text not null, weight numeric not null check(weight>=0), max_score numeric not null default 100, is_active boolean default true);
create table if not exists ngaji_assessments (id bigint generated always as identity primary key, window_id bigint references ngaji_assessment_windows(id), student_id uuid references ngaji_students(id), assessor_teacher_id uuid references ngaji_teachers(id), total_score numeric, comments text, status text default 'draft' check(status in ('draft','submitted')), submitted_at timestamptz, updated_at timestamptz default now(), unique(window_id,student_id,assessor_teacher_id));
create table if not exists ngaji_assessment_scores (id bigint generated always as identity primary key, assessment_id bigint references ngaji_assessments(id) on delete cascade, item_id bigint references ngaji_assessment_items(id), score numeric not null, unique(assessment_id,item_id));
create table if not exists ngaji_calendar (id bigint generated always as identity primary key, title text not null, event_type text not null check(event_type in ('public_holiday','school_holiday','exam','assessment','class','other')), start_date date not null, end_date date, details text, is_public boolean default true);
create table if not exists ngaji_announcements (id bigint generated always as identity primary key, title text not null, body text, starts_at timestamptz, ends_at timestamptz, is_published boolean default false, created_by uuid references ngaji_users(id));
create table if not exists ngaji_documents (id bigint generated always as identity primary key, title text not null, url text not null, visibility text default 'public' check(visibility in ('public','student','teacher','admin')), uploaded_by uuid references ngaji_users(id), created_at timestamptz default now());
create table if not exists ngaji_settings (key text primary key, value jsonb not null, updated_at timestamptz default now(), updated_by uuid references ngaji_users(id));
create table if not exists ngaji_audit_log (id bigint generated always as identity primary key, actor_user_id uuid references ngaji_users(id), action text not null, entity_type text, entity_id text, before_data jsonb, after_data jsonb, created_at timestamptz default now());
insert into ngaji_assessment_items(item_key,label,weight,max_score) values ('attendance','Kehadiran',30,30),('tajwid','Tajwid',15,15),('makhraj','Makhraj',12,12),('fluency','Kelancaran',10,10),('adab','Adab & Sebutan',5,5),('memorisation','Hafazan / Sasaran',8,8),('participation','Penglibatan',20,20) on conflict(item_key) do nothing;
insert into ngaji_users(role,login_id,password_hash) values ('student','101010101010',crypt('123456',gen_salt('bf'))),('teacher','01234567890',crypt('123456',gen_salt('bf'))),('admin','ngaji_admin',crypt('123456',gen_salt('bf'))) on conflict(login_id) do nothing;
-- RLS asas. Polisi produksi perlu disesuaikan dengan Supabase Auth JWT role/user mapping.
alter table ngaji_students enable row level security; alter table ngaji_teachers enable row level security; alter table ngaji_attendance enable row level security; alter table ngaji_assessments enable row level security; alter table ngaji_assessment_scores enable row level security;
